// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wanjun.package.proto

#ifndef PROTOBUF_INCLUDED_wanjun_2epackage_2eproto
#define PROTOBUF_INCLUDED_wanjun_2epackage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.header.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_wanjun_2epackage_2eproto 

namespace protobuf_wanjun_2epackage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_wanjun_2epackage_2eproto
namespace wanjun {
class WjPackage;
class WjPackageDefaultTypeInternal;
extern WjPackageDefaultTypeInternal _WjPackage_default_instance_;
}  // namespace wanjun
namespace google {
namespace protobuf {
template<> ::wanjun::WjPackage* Arena::CreateMaybeMessage<::wanjun::WjPackage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wanjun {

// ===================================================================

class WjPackage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:wanjun.WjPackage) */ {
 public:
  WjPackage();
  virtual ~WjPackage();

  WjPackage(const WjPackage& from);

  inline WjPackage& operator=(const WjPackage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WjPackage(WjPackage&& from) noexcept
    : WjPackage() {
    *this = ::std::move(from);
  }

  inline WjPackage& operator=(WjPackage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WjPackage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WjPackage* internal_default_instance() {
    return reinterpret_cast<const WjPackage*>(
               &_WjPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WjPackage* other);
  friend void swap(WjPackage& a, WjPackage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WjPackage* New() const final {
    return CreateMaybeMessage<WjPackage>(NULL);
  }

  WjPackage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WjPackage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WjPackage& from);
  void MergeFrom(const WjPackage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WjPackage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string privateData = 2;
  bool has_privatedata() const;
  void clear_privatedata();
  static const int kPrivateDataFieldNumber = 2;
  const ::std::string& privatedata() const;
  void set_privatedata(const ::std::string& value);
  #if LANG_CXX11
  void set_privatedata(::std::string&& value);
  #endif
  void set_privatedata(const char* value);
  void set_privatedata(const char* value, size_t size);
  ::std::string* mutable_privatedata();
  ::std::string* release_privatedata();
  void set_allocated_privatedata(::std::string* privatedata);

  // required .common.header head = 1;
  bool has_head() const;
  void clear_head();
  static const int kHeadFieldNumber = 1;
  private:
  const ::common::header& _internal_head() const;
  public:
  const ::common::header& head() const;
  ::common::header* release_head();
  ::common::header* mutable_head();
  void set_allocated_head(::common::header* head);

  // @@protoc_insertion_point(class_scope:wanjun.WjPackage)
 private:
  void set_has_head();
  void clear_has_head();
  void set_has_privatedata();
  void clear_has_privatedata();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr privatedata_;
  ::common::header* head_;
  friend struct ::protobuf_wanjun_2epackage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WjPackage

// required .common.header head = 1;
inline bool WjPackage::has_head() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WjPackage::set_has_head() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WjPackage::clear_has_head() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::common::header& WjPackage::_internal_head() const {
  return *head_;
}
inline const ::common::header& WjPackage::head() const {
  const ::common::header* p = head_;
  // @@protoc_insertion_point(field_get:wanjun.WjPackage.head)
  return p != NULL ? *p : *reinterpret_cast<const ::common::header*>(
      &::common::_header_default_instance_);
}
inline ::common::header* WjPackage::release_head() {
  // @@protoc_insertion_point(field_release:wanjun.WjPackage.head)
  clear_has_head();
  ::common::header* temp = head_;
  head_ = NULL;
  return temp;
}
inline ::common::header* WjPackage::mutable_head() {
  set_has_head();
  if (head_ == NULL) {
    auto* p = CreateMaybeMessage<::common::header>(GetArenaNoVirtual());
    head_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wanjun.WjPackage.head)
  return head_;
}
inline void WjPackage::set_allocated_head(::common::header* head) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(head_);
  }
  if (head) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      head = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    set_has_head();
  } else {
    clear_has_head();
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:wanjun.WjPackage.head)
}

// required string privateData = 2;
inline bool WjPackage::has_privatedata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WjPackage::set_has_privatedata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WjPackage::clear_has_privatedata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WjPackage::clear_privatedata() {
  privatedata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_privatedata();
}
inline const ::std::string& WjPackage::privatedata() const {
  // @@protoc_insertion_point(field_get:wanjun.WjPackage.privateData)
  return privatedata_.GetNoArena();
}
inline void WjPackage::set_privatedata(const ::std::string& value) {
  set_has_privatedata();
  privatedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wanjun.WjPackage.privateData)
}
#if LANG_CXX11
inline void WjPackage::set_privatedata(::std::string&& value) {
  set_has_privatedata();
  privatedata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wanjun.WjPackage.privateData)
}
#endif
inline void WjPackage::set_privatedata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_privatedata();
  privatedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wanjun.WjPackage.privateData)
}
inline void WjPackage::set_privatedata(const char* value, size_t size) {
  set_has_privatedata();
  privatedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wanjun.WjPackage.privateData)
}
inline ::std::string* WjPackage::mutable_privatedata() {
  set_has_privatedata();
  // @@protoc_insertion_point(field_mutable:wanjun.WjPackage.privateData)
  return privatedata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WjPackage::release_privatedata() {
  // @@protoc_insertion_point(field_release:wanjun.WjPackage.privateData)
  if (!has_privatedata()) {
    return NULL;
  }
  clear_has_privatedata();
  return privatedata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WjPackage::set_allocated_privatedata(::std::string* privatedata) {
  if (privatedata != NULL) {
    set_has_privatedata();
  } else {
    clear_has_privatedata();
  }
  privatedata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), privatedata);
  // @@protoc_insertion_point(field_set_allocated:wanjun.WjPackage.privateData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace wanjun

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_wanjun_2epackage_2eproto
